### ISSUE TITLE
Library methods shouldn't use tokio::main attribute

### ISSUE THREAD

**Issue by vrobweis** [alt-art/genius-rs#3]
https://github.com/alt-art/genius-rs/blob/f9636b1910901347910becaf4687e25e64e4b2ca/src/lib.rs#L87
https://github.com/alt-art/genius-rs/blob/f9636b1910901347910becaf4687e25e64e4b2ca/src/lib.rs#L76

Making the Genius methods both labeled with ![tokio::main] is problematic, since effectively it makes them unusable as library calls. They're async functions that can't be executed by the user's runtime, you reproduce the tokio runtime with every call of those methods. It dodges compiler issues, okay, but in practice this barely works for performance, and makes using the methods more unwieldy. Try instead making your test methods use the tokio test attribute.

**Comment by alt-art** [comment]
Yes, the right thing would be to make the library not consume tokio::main but deliver itself to the user's runtime, but I know little about tokio and I did it this way without knowing it would be possible if you want to introduce me this way I would be super grateful.

**Comment by vrobweis** [comment]
[This pull request](https://github.com/alt-art/genius-rs/pull/4) should resolve the issue. It replaces the test attributes with the tokio test attributes and makes the tests asynchronous so that only the tests use tokio. The actual library calls should now be runtime-agnostic, and the user could use tokio, futures, or async_std, and so on.

**Comment by alt-art** [comment]
This is my first merge, that's why i look like an idiot.
